/**
 * HTML tag name constants.
 *
 * This file provides constants for HTML tag names.
 * It replaces the Closure Library's dom/tagname module.
 *
 * @license
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * HTML tag names.
 */
export enum TagName {
  A = 'A',
  ABBR = 'ABBR',
  ACRONYM = 'ACRONYM',
  ADDRESS = 'ADDRESS',
  APPLET = 'APPLET',
  AREA = 'AREA',
  ARTICLE = 'ARTICLE',
  ASIDE = 'ASIDE',
  AUDIO = 'AUDIO',
  B = 'B',
  BASE = 'BASE',
  BASEFONT = 'BASEFONT',
  BDI = 'BDI',
  BDO = 'BDO',
  BIG = 'BIG',
  BLOCKQUOTE = 'BLOCKQUOTE',
  BODY = 'BODY',
  BR = 'BR',
  BUTTON = 'BUTTON',
  CANVAS = 'CANVAS',
  CAPTION = 'CAPTION',
  CENTER = 'CENTER',
  CITE = 'CITE',
  CODE = 'CODE',
  COL = 'COL',
  COLGROUP = 'COLGROUP',
  COMMAND = 'COMMAND',
  DATA = 'DATA',
  DATALIST = 'DATALIST',
  DD = 'DD',
  DEL = 'DEL',
  DETAILS = 'DETAILS',
  DFN = 'DFN',
  DIALOG = 'DIALOG',
  DIR = 'DIR',
  DIV = 'DIV',
  DL = 'DL',
  DT = 'DT',
  EM = 'EM',
  EMBED = 'EMBED',
  FIELDSET = 'FIELDSET',
  FIGCAPTION = 'FIGCAPTION',
  FIGURE = 'FIGURE',
  FONT = 'FONT',
  FOOTER = 'FOOTER',
  FORM = 'FORM',
  FRAME = 'FRAME',
  FRAMESET = 'FRAMESET',
  H1 = 'H1',
  H2 = 'H2',
  H3 = 'H3',
  H4 = 'H4',
  H5 = 'H5',
  H6 = 'H6',
  HEAD = 'HEAD',
  HEADER = 'HEADER',
  HGROUP = 'HGROUP',
  HR = 'HR',
  HTML = 'HTML',
  I = 'I',
  IFRAME = 'IFRAME',
  IMG = 'IMG',
  INPUT = 'INPUT',
  INS = 'INS',
  ISINDEX = 'ISINDEX',
  KBD = 'KBD',
  KEYGEN = 'KEYGEN',
  LABEL = 'LABEL',
  LEGEND = 'LEGEND',
  LI = 'LI',
  LINK = 'LINK',
  MAP = 'MAP',
  MARK = 'MARK',
  MATH = 'MATH',
  MENU = 'MENU',
  META = 'META',
  METER = 'METER',
  NAV = 'NAV',
  NOFRAMES = 'NOFRAMES',
  NOSCRIPT = 'NOSCRIPT',
  OBJECT = 'OBJECT',
  OL = 'OL',
  OPTGROUP = 'OPTGROUP',
  OPTION = 'OPTION',
  OUTPUT = 'OUTPUT',
  P = 'P',
  PARAM = 'PARAM',
  PICTURE = 'PICTURE',
  PRE = 'PRE',
  PROGRESS = 'PROGRESS',
  Q = 'Q',
  RP = 'RP',
  RT = 'RT',
  RUBY = 'RUBY',
  S = 'S',
  SAMP = 'SAMP',
  SCRIPT = 'SCRIPT',
  SECTION = 'SECTION',
  SELECT = 'SELECT',
  SMALL = 'SMALL',
  SOURCE = 'SOURCE',
  SPAN = 'SPAN',
  STRIKE = 'STRIKE',
  STRONG = 'STRONG',
  STYLE = 'STYLE',
  SUB = 'SUB',
  SUMMARY = 'SUMMARY',
  SUP = 'SUP',
  SVG = 'SVG',
  TABLE = 'TABLE',
  TBODY = 'TBODY',
  TD = 'TD',
  TEMPLATE = 'TEMPLATE',
  TEXTAREA = 'TEXTAREA',
  TFOOT = 'TFOOT',
  TH = 'TH',
  THEAD = 'THEAD',
  TIME = 'TIME',
  TITLE = 'TITLE',
  TR = 'TR',
  TRACK = 'TRACK',
  TT = 'TT',
  U = 'U',
  UL = 'UL',
  VAR = 'VAR',
  VIDEO = 'VIDEO',
  WBR = 'WBR'
}
